# Generated by Django 4.2.7 on 2023-11-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoEditor', '0002_remove_video_id_video_video_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
