# Generated by Django 4.2.7 on 2023-11-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoEditor', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='parent_video',
            field=models.IntegerField(null=True),
        ),
    ]
