# Generated by Django 4.2.7 on 2023-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoEditor', '0005_alter_video_parent_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleVideos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_video_id', models.IntegerField()),
                ('bubble_video_id', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('videofile', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
